#pragma once

///
/// Generic
///

#define ARM_COND_SHIFT /*  */ 28
#define ARM_COND_MASK /*   */ 0xf0000000u

#define ARM_GET_COND(inst) (((inst)) & ARM_COND_MASK) // optimización: no shift

///
/// Data processing and FSR transfer
///

#define ARM_FSR_OPCODE_SHIFT /*   */ 21
#define ARM_FSR_OPCODE_MASK /*    */ (0xfu << ARM_FSR_OPCODE_SHIFT)

#define ARM_FSR_S_SHIFT /*        */ 20
#define ARM_FSR_S_MASK /*         */ (1u << ARM_FSR_S_SHIFT)

#define ARM_FSR_RN_SHIFT /*       */ 16
#define ARM_FSR_RN_MASK /*        */ (0xfu << ARM_FSR_RN_SHIFT)

#define ARM_FSR_RD_SHIFT /*       */ 12
#define ARM_FSR_RD_MASK /*        */ (0xfu << ARM_FSR_RD_SHIFT)

#define ARM_FSR_OPERAND2_SHIFT /* */ 0
#define ARM_FSR_OPERAND2_MASK /*  */ ((1u << 12) - 1)

#define ARM_FSR_GET_OPCODE(inst) (((inst)) & ARM_FSR_OPCODE_MASK)

#define ARM_FSR_IS_S(inst) ((((inst)) & ARM_FSR_S_MASK) != 0)

#define ARM_FSR_GET_RN(inst) ((((inst)) & ARM_FSR_RN_MASK) >> ARM_FSR_RN_SHIFT)
#define ARM_FSR_GET_RD(inst) ((((inst)) & ARM_FSR_RD_MASK) >> ARM_FSR_RD_SHIFT)
#define ARM_FSR_GET_OPERAND2(inst) (((inst)) & ARM_FSR_OPERAND2_MASK)

///
/// Multiply
///

#define ARM_MULTIPLY_A_SHIFT /*    */ 21
#define ARM_MULTIPLY_A_MASK /*     */ (1u << ARM_MULTIPLY_A_SHIFT)

#define ARM_MULTIPLY_S_SHIFT /*    */ ARM_FSR_S_SHIFT
#define ARM_MULTIPLY_S_MASK /*     */ ARM_FSR_S_MASK

#define ARM_MULTIPLY_RD_SHIFT /*   */ ARM_FSR_RN_SHIFT
#define ARM_MULTIPLY_RD_MASK /*    */ ARM_FSR_RN_MASK

#define ARM_MULTIPLY_RN_SHIFT /*   */ ARM_FSR_RD_SHIFT
#define ARM_MULTIPLY_RN_MASK /*    */ ARM_FSR_RD_MASK

#define ARM_MULTIPLY_RS_SHIFT /*   */ 8
#define ARM_MULTIPLY_RS_MASK /*    */ (0xfu << ARM_MULTIPLY_RS_SHIFT)

#define ARM_MULTIPLY_RM_SHIFT /*   */ 0
#define ARM_MULTIPLY_RM_MASK /*    */ (0xfu)

#define ARM_MULTIPLY_IS_A(inst) ((((inst)) & ARM_MULTIPLY_A_MASK) != 0)
#define ARM_MULTIPLY_IS_S(inst) (ARM_FSR_IS_S(inst))

#define ARM_MULTIPLY_GET_RD(inst) (ARM_FSR_GET_RN(inst))
#define ARM_MULTIPLY_GET_RN(inst) (ARM_FSR_GET_RD(inst))
#define ARM_MULTIPLY_GET_RS(inst)                                              \
  ((((inst)) & (ARM_MULTIPLY_RS_MASK)) >> ARM_MULTIPLY_RS_SHIFT)
#define ARM_MULTIPLY_GET_RM(inst) (((inst)) & ARM_MULTIPLY_RM_MASK)

///
/// Multiply long
///

#define ARM_MULTIPLY_LONG_U_SHIFT /*    */ 22
#define ARM_MULTIPLY_LONG_U_MASK /*     */ (1u << ARM_MULTIPLY_LONG_U_SHIFT)

#define ARM_MULTIPLY_LONG_A_SHIFT /*    */ ARM_MULTIPLY_A_SHIFT
#define ARM_MULTIPLY_LONG_A_MASK /*     */ ARM_MULTIPLY_A_MASK

#define ARM_MULTIPLY_LONG_S_SHIFT /*    */ ARM_MULTIPLY_S_SHIFT
#define ARM_MULTIPLY_LONG_S_MASK /*     */ ARM_MULTIPLY_S_MASK

#define ARM_MULTIPLY_LONG_RDHI_SHIFT /* */ ARM_MULTIPLY_RD_SHIFT
#define ARM_MULTIPLY_LONG_RDHI_MASK /*  */ ARM_MULTIPLY_RD_MASK

#define ARM_MULTIPLY_LONG_RDLO_SHIFT /* */ ARM_MULTIPLY_RN_SHIFT
#define ARM_MULTIPLY_LONG_RDLO_MASK /*  */ ARM_MULTIPLY_RN_MASK

#define ARM_MULTIPLY_LONG_RN_SHIFT /*   */ ARM_MULTIPLY_RS_SHIFT
#define ARM_MULTIPLY_LONG_RN_MASK /*    */ ARM_MULTIPLY_RS_MASK

#define ARM_MULTIPLY_LONG_RM_SHIFT /*   */ ARM_MULTIPLY_RM_SHIFT
#define ARM_MULTIPLY_LONG_RM_MASK /*    */ ARM_MULTIPLY_RM_MASK

#define ARM_MULTIPLY_LONG_IS_U(inst)                                           \
  ((((inst)) & ARM_MULTIPLY_LONG_U_MASK) != 0)
#define ARM_MULTIPLY_LONG_IS_A(inst) (ARM_MULTIPLY_IS_A(inst))
#define ARM_MULTIPLY_LONG_IS_S(inst) (ARM_MULTIPLY_IS_S(inst))

#define ARM_MULTIPLY_LONG_GET_RDHI(inst) (ARM_MULTIPLY_GET_RD(inst))
#define ARM_MULTIPLY_LONG_GET_RDLO(inst) (ARM_MULTIPLY_GET_RN(inst))
#define ARM_MULTIPLY_LONG_GET_RN(inst) (ARM_MULTIPLY_GET_RS(inst))
#define ARM_MULTIPLY_LONG_GET_RM(inst) (ARM_MULTIPLY_GET_RM(inst))

///
/// Single data swap
///

#define ARM_SINGLE_DATA_SWAP_B_SHIFT /*    */ ARM_MULTIPLY_LONG_U_SHIFT
#define ARM_SINGLE_DATA_SWAP_B_MASK /*     */ ARM_MULTIPLY_LONG_U_MASK

#define ARM_SINGLE_DATA_SWAP_RN_SHIFT /*   */ ARM_FSR_RN_SHIFT
#define ARM_SINGLE_DATA_SWAP_RN_MASK /*    */ ARM_FSR_RN_MASK

#define ARM_SINGLE_DATA_SWAP_RD_SHIFT /*   */ ARM_FSR_RD_SHIFT
#define ARM_SINGLE_DATA_SWAP_RD_MASK /*    */ ARM_FSR_RD_MASK

#define ARM_SINGLE_DATA_SWAP_RM_SHIFT /*   */ ARM_MULTIPLY_RM_SHIFT
#define ARM_SINGLE_DATA_SWAP_RM_MASK /*    */ ARM_MULTIPLY_RM_MASK

#define ARM_SINGLE_DATA_SWAP_IS_U(inst)                                        \
  ((((inst)) & ARM_SINGLE_DATA_SWAP_B_MASK) != 0)

#define ARM_SINGLE_DATA_SWAP_GET_RN(inst) (ARM_FSR_GET_RN(inst))
#define ARM_SINGLE_DATA_SWAP_GET_RD(inst) (ARM_FSR_GET_RD(inst))
#define ARM_SINGLE_DATA_SWAP_GET_RM(inst) (ARM_MULTIPLY_GET_RM(inst))

///
/// Branch and Exchange
///

#define ARM_BRANCH_AND_EXCHANGE_RN_SHIFT /*   */ ARM_MULTIPLY_RM_SHIFT
#define ARM_BRANCH_AND_EXCHANGE_RN_MASK /*    */ ARM_MULTIPLY_RM_MASK

#define ARM_BRANCH_AND_EXCHANGE_GET_RM(inst) (ARM_MULTIPLY_GET_RM(inst))

///
/// Halfword data transfer, register offset
///

#define ARM_HALF_DATA_TRANSFER_REGISTER_P_SHIFT 24
#define ARM_HALF_DATA_TRANSFER_REGISTER_P_MASK                                 \
  (1u << ARM_HALF_DATA_TRANSFER_REGISTER_P_SHIFT)

#define ARM_HALF_DATA_TRANSFER_REGISTER_U_SHIFT 23
#define ARM_HALF_DATA_TRANSFER_REGISTER_U_MASK                                 \
  (1u << ARM_HALF_DATA_TRANSFER_REGISTER_U_SHIFT)

#define ARM_HALF_DATA_TRANSFER_REGISTER_W_SHIFT /*    */ ARM_MULTIPLY_A_SHIFT
#define ARM_HALF_DATA_TRANSFER_REGISTER_W_MASK /*     */ ARM_MULTIPLY_A_MASK

#define ARM_HALF_DATA_TRANSFER_REGISTER_L_SHIFT /*    */ ARM_FSR_S_SHIFT
#define ARM_HALF_DATA_TRANSFER_REGISTER_L_MASK /*     */ ARM_FSR_S_MASK

#define ARM_HALF_DATA_TRANSFER_REGISTER_RN_SHIFT /*   */ ARM_FSR_RN_SHIFT
#define ARM_HALF_DATA_TRANSFER_REGISTER_RN_MASK /*    */ ARM_FSR_RN_MASK

#define ARM_HALF_DATA_TRANSFER_REGISTER_RD_SHIFT /*   */ ARM_FSR_RD_SHIFT
#define ARM_HALF_DATA_TRANSFER_REGISTER_RD_MASK /*    */ ARM_FSR_RD_MASK

#define ARM_HALF_DATA_TRANSFER_REGISTER_S_SHIFT 6
#define ARM_HALF_DATA_TRANSFER_REGISTER_S_MASK                                 \
  (1u << ARM_HALF_DATA_TRANSFER_REGISTER_S_SHIFT)

#define ARM_HALF_DATA_TRANSFER_REGISTER_H_SHIFT 5
#define ARM_HALF_DATA_TRANSFER_REGISTER_H_MASK                                 \
  (1u << ARM_HALF_DATA_TRANSFER_REGISTER_H_SHIFT)

#define ARM_HALF_DATA_TRANSFER_REGISTER_RM_SHIFT /*   */ ARM_MULTIPLY_RM_SHIFT
#define ARM_HALF_DATA_TRANSFER_REGISTER_RM_MASK /*    */ ARM_MULTIPLY_RM_MASK

#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_P(inst)                             \
  ((((inst)) & ARM_HALF_DATA_TRANSFER_REGISTER_P_MASK) != 0)

#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_U(inst)                             \
  ((((inst)) & ARM_HALF_DATA_TRANSFER_REGISTER_U_MASK) != 0)

#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_W(inst) (ARM_MULTIPLY_IS_A(inst))
#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_L(inst) (ARM_FSR_IS_S(inst))

#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_S(inst)                             \
  ((((inst)) & ARM_HALF_DATA_TRANSFER_REGISTER_S_MASK) != 0)

#define ARM_HALF_DATA_TRANSFER_REGISTER_IS_H(inst)                             \
  ((((inst)) & ARM_HALF_DATA_TRANSFER_REGISTER_H_MASK) != 0)

#define ARM_HALF_DATA_TRANSFER_REGISTER_GET_RN(inst) (ARM_FSR_GET_RN(inst))
#define ARM_HALF_DATA_TRANSFER_REGISTER_GET_RD(inst) (ARM_FSR_GET_RD(inst))
#define ARM_HALF_DATA_TRANSFER_REGISTER_GET_RM(inst) (ARM_MULTIPLY_GET_RM(inst))

///
/// Halfword data transfer, immediate offset
///

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_P_SHIFT                               \
  ARM_HALF_DATA_TRANSFER_REGISTER_P_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_P_MASK                                \
  ARM_HALF_DATA_TRANSFER_REGISTER_P_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_U_SHIFT                               \
  ARM_HALF_DATA_TRANSFER_REGISTER_U_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_U_MASK                                \
  ARM_HALF_DATA_TRANSFER_REGISTER_U_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_W_SHIFT /*    */ ARM_MULTIPLY_A_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_W_MASK /*     */ ARM_MULTIPLY_A_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_L_SHIFT /*    */ ARM_FSR_S_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_L_MASK /*     */ ARM_FSR_S_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_RN_SHIFT /*   */ ARM_FSR_RN_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_RN_MASK /*    */ ARM_FSR_RN_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_RD_SHIFT /*   */ ARM_FSR_RD_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_RD_MASK /*    */ ARM_FSR_RD_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_S_SHIFT                               \
  ARM_HALF_DATA_TRANSFER_REGISTER_S_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_S_MASK                                \
  ARM_HALF_DATA_TRANSFER_REGISTER_S_MASK

#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_H_SHIFT                               \
  ARM_HALF_DATA_TRANSFER_REGISTER_H_SHIFT
#define ARM_HALF_DATA_TRANSFER_IMMEDIATE_H_MASK                                \
  ARM_HALF_DATA_TRANSFER_REGISTER_H_MASK

// falta operaciones y offset partido
