#pragma once

#define NEOGBA_K_BLOCK_BIT_SIZE 32
#define NEOGBA_K_BLOCK_INDEX_MASK 8
#define NEOGBA_K_GBABLOCKOFFSETMASK K_BLOCK_BIT_SIZE - K_BLOCK_INDEX_MASK
#define NEOGBA_K_LENGTH_REGISTERS_IN_MODE 18
#define NEOGBA_K_TOTAL_REGISTERS 37
#define NEOGBA_K_MASK_MODE 0x1f
